{{- if and .Values.gateway.config (not .Values.gateway.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keeper-gateway.fullname" . }}-config
  labels:
    {{- include "keeper-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  gateway-config: {{ .Values.gateway.config | quote }}
{{- end }}
{{- if and .Values.healthCheck.authToken (not .Values.healthCheck.existingAuthTokenSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keeper-gateway.fullname" . }}-health-token
  labels:
    {{- include "keeper-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  health-check-token: {{ .Values.healthCheck.authToken | quote }}
{{- end }}
{{- if and .Values.ai.enabled .Values.ai.apiKey (not .Values.ai.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keeper-gateway.fullname" . }}-ai
  labels:
    {{- include "keeper-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  ai-api-key: {{ .Values.ai.apiKey | quote }}
{{- end }}
